problem Statement :Compare model with and without Normalization

 GROUP MEMBER :
name                            ROll NUMBER  GR NUMBE
1.Chinmay Jayendra Deotale         71          11910759
2.Geetai Charde                    60          12020007
3.Abhijeet Chine                   67          12020187
4. Nishit chaudhari                64          11910054
5.Akhil Bhalgat                    44          1710023

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.python.data import Dataset
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
from keras import layers

In [2]:
#Read the data from csv file
df = pd.read_csv('covtype.csv')
df

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,5
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,5
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,2
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,2
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,...,0,0,0,0,0,0,0,0,0,3
581008,2391,152,19,67,12,95,240,237,119,845,...,0,0,0,0,0,0,0,0,0,3
581009,2386,159,17,60,7,90,236,241,130,854,...,0,0,0,0,0,0,0,0,0,3
581010,2384,170,15,60,5,90,230,245,143,864,...,0,0,0,0,0,0,0,0,0,3
581011,2383,165,13,60,4,67,231,244,141,875,...,0,0,0,0,0,0,0,0,0,3

In [3]:
#Select predictors
x = df[df.columns[:54]]
x

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,2596,51,3,258,0,510,221,232,148,6279,...,0,0,0,0,0,0,0,0,0,0
1,2590,56,2,212,-6,390,220,235,151,6225,...,0,0,0,0,0,0,0,0,0,0
2,2804,139,9,268,65,3180,234,238,135,6121,...,0,0,0,0,0,0,0,0,0,0
3,2785,155,18,242,118,3090,238,238,122,6211,...,0,0,0,0,0,0,0,0,0,0
4,2595,45,2,153,-1,391,220,234,150,6172,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581007,2396,153,20,85,17,108,240,237,118,837,...,0,0,0,0,0,0,0,0,0,0
581008,2391,152,19,67,12,95,240,237,119,845,...,0,0,0,0,0,0,0,0,0,0
581009,2386,159,17,60,7,90,236,241,130,854,...,0,0,0,0,0,0,0,0,0,0
581010,2384,170,15,60,5,90,230,245,143,864,...,0,0,0,0,0,0,0,0,0,0
581011,2383,165,13,60,4,67,231,244,141,875,...,0,0,0,0,0,0,0,0,0,0

In [4]:
#Target variable 
y = df.Cover_Type
y

0         5
1         5
2         2
3         2
4         5
         ..
581007    3
581008    3
581009    3
581010    3
581011    3
Name: Cover_Type, Length: 581012, dtype: int64

In [5]:
#Split data into train and test 
x_train, x_test, y_train, y_test = train_test_split(x, y , train_size = 0.7, random_state =  90)

In [6]:
'''As y variable is multi class categorical variable, hence using softmax as activation function and sparse-categorical cross entropy as loss function.'''
model = keras.Sequential([
 keras.layers.Dense(64, activation=tf.nn.relu,                  
 input_shape=(x_train.shape[1],)),
 keras.layers.Dense(64, activation=tf.nn.relu),
 keras.layers.Dense(8, activation=  'softmax')
 ])

In [7]:
model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
history1 = model.fit(
 x_train, y_train,
 epochs= 26, batch_size = 60,
 validation_data = (x_test, y_test))

Epoch 1/26
6779/6779 [==============================] - 18s 3ms/step - loss: 4.0010 - accuracy: 0.5762 - val_loss: 1.0982 - val_accuracy: 0.6689
Epoch 2/26
6779/6779 [==============================] - 18s 3ms/step - loss: 1.2194 - accuracy: 0.6403 - val_loss: 0.7991 - val_accuracy: 0.6958
Epoch 3/26
6779/6779 [==============================] - 18s 3ms/step - loss: 0.8109 - accuracy: 0.6793 - val_loss: 0.6619 - val_accuracy: 0.7077
Epoch 4/26
6779/6779 [==============================] - 18s 3ms/step - loss: 0.6803 - accuracy: 0.7099 - val_loss: 0.6424 - val_accuracy: 0.7281
Epoch 5/26
6779/6779 [==============================] - 17s 3ms/step - loss: 0.6285 - accuracy: 0.7291 - val_loss: 0.5908 - val_accuracy: 0.7466
Epoch 6/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.6013 - accuracy: 0.7410 - val_loss: 0.5691 - val_accuracy: 0.7581
Epoch 7/26
6779/6779 [==============================] - 17s 2ms/step - loss: 0.5830 - accuracy: 0.7476 - val_loss: 0.6001 - val_accuracy: 0.7440
Epoch 8/26
6779/6779 [==============================] - 17s 3ms/step - loss: 0.5689 - accuracy: 0.7543 - val_loss: 0.5768 - val_accuracy: 0.7471
Epoch 9/26
6779/6779 [==============================] - 15s 2ms/step - loss: 0.5578 - accuracy: 0.7596 - val_loss: 0.5555 - val_accuracy: 0.7662
Epoch 10/26
6779/6779 [==============================] - 15s 2ms/step - loss: 0.5515 - accuracy: 0.7620 - val_loss: 0.5205 - val_accuracy: 0.7742
Epoch 11/26
6779/6779 [==============================] - 15s 2ms/step - loss: 0.5440 - accuracy: 0.7659 - val_loss: 0.5309 - val_accuracy: 0.7742
Epoch 12/26
6779/6779 [==============================] - 16s 2ms/step - loss: 0.5384 - accuracy: 0.7691 - val_loss: 0.5496 - val_accuracy: 0.7619
Epoch 13/26
6779/6779 [==============================] - 17s 3ms/step - loss: 0.5329 - accuracy: 0.7721 - val_loss: 0.5231 - val_accuracy: 0.7804
Epoch 14/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.5292 - accuracy: 0.7745 - val_loss: 0.5364 - val_accuracy: 0.7718
Epoch 15/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.5246 - accuracy: 0.7758 - val_loss: 0.5127 - val_accuracy: 0.7815
Epoch 16/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.5184 - accuracy: 0.7795 - val_loss: 0.4993 - val_accuracy: 0.7904
Epoch 17/26
6779/6779 [==============================] - 20s 3ms/step - loss: 0.5156 - accuracy: 0.7806 - val_loss: 0.5166 - val_accuracy: 0.7821
Epoch 18/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.5120 - accuracy: 0.7820 - val_loss: 0.5462 - val_accuracy: 0.7676
Epoch 19/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.5115 - accuracy: 0.7824 - val_loss: 0.5152 - val_accuracy: 0.7795
Epoch 20/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.5085 - accuracy: 0.7835 - val_loss: 0.5120 - val_accuracy: 0.7799
Epoch 21/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.5088 - accuracy: 0.7839 - val_loss: 0.5447 - val_accuracy: 0.7676
Epoch 22/26
6779/6779 [==============================] - 20s 3ms/step - loss: 0.5055 - accuracy: 0.7845 - val_loss: 0.4987 - val_accuracy: 0.7908
Epoch 23/26
6779/6779 [==============================] - 18s 3ms/step - loss: 0.5021 - accuracy: 0.7869 - val_loss: 0.4983 - val_accuracy: 0.7877
Epoch 24/26
6779/6779 [==============================] - 20s 3ms/step - loss: 0.5007 - accuracy: 0.7869 - val_loss: 0.4784 - val_accuracy: 0.7967
Epoch 25/26
6779/6779 [==============================] - 21s 3ms/step - loss: 0.4995 - accuracy: 0.7880 - val_loss: 0.5140 - val_accuracy: 0.7824
Epoch 26/26
6779/6779 [==============================] - 19s 3ms/step - loss: 0.4986 - accuracy: 0.7888 - val_loss: 0.4746 - val_accuracy: 0.7996